language: python
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  # Ubuntu 14.04 does not have ffmpeg in the official package list
  # We therefore download use the static build
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - tar xvf ffmpeg-release-64bit-static.tar.xz
  - cd ./ffmpeg-*
  - sudo cp ff* qt-faststart /usr/local/bin/
  - cd .. 
install:
  # Some of this code is taken from https://github.com/keras-team/keras/blob/master/.travis.yml
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - travis_retry conda install -y python=3.6
  - travis_retry conda install numpy tqdm pytest pytest-runner
  - travis_retry conda install ffmpeg-python -c mrinaljain17
  - pip install -e .
script:
  - pytest
after_success:
  - pip uninstall -y mydia
