language: python
sudo: required
dist: trusty
stages:
  - Test
  - Docs
before_install:
  # Some of the code below is taken from https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - travis_retry conda install -y python=3.6
  - travis_retry conda install -y numpy tqdm pytest pytest-runner
  - travis_retry conda install -y ffmpeg ffmpeg-python -c mrinaljain17
install:
  - pip install -e .
script:  # Performed in jobs
after_success:  # Nothing to do

jobs:
  include:
    - stage: Test
      script: pytest
    - stage: Docs
      # Use previously defined before_install
      before_install: *before_install
      install:
        - travis_retry conda install -y sphinx pillow matplotlib
        - pip install sphinx-gallery
        - pip install .
      script:
        - cd docs && make html
        - touch files/html/.nojekyll
      after_success: # Nothing to do
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docs/files/html
        on:
          branch: master
