{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ../..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - pip
    - setuptools
    - python    
    - ffmpeg-python
    - numpy
    - tqdm
    - pytest-runner
  run:
    - ffmpeg-python
    - numpy
    - tqdm
    - python

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
  doc_url: https://mrinaljain17.github.io/mydia/
