{% set name = "mydia" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56c6e89cb4640e29b83941373ed3179becea259b4fd9cd4377ac6b503386a24b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - pip
    - setuptools
    - python    
    - ffmpeg-python
    - numpy
    - tqdm
  run:
    - ffmpeg-python
    - numpy
    - tqdm
    - python

about:
  home: https://github.com/MrinalJain17/mydia
  license: MIT License
  license_family: MIT
  license_file: 
  summary: A simple and efficient wrapper for reading videos as NumPy tensors
  doc_url: https://mrinaljain17.github.io/mydia/
